/****************************************
 * This file is part of UNIX Guide for the Perplexed project.
 * Copyright (C) 2014 by Assaf Gordon <assafgordon@gmail.com>
 * Released under GPLv3 or later.
 ****************************************/

/*
This tester compares the two POSIX Shell parsers:
1. The parser dynamically generated during runtime,
   by loading PegJS and compiling the syntax
   (see 'utils/shell_parser_loader.js').

2. The pre-compiled parser script,
   generated by running 'pegjs' in the Makefile
   (see 'shell/posix_shell_parser.js' and 'SHELL_PARSER' rule in the make file).

The two parsers should generate the exact same parse-tree structure.
(as a by-product this also tests the Makefile auto-generation of the
pre-compiled parser).
*/

"use strict";

var count_pass = 0 ;
var count_fail = 0 ;
var seen_tests = {};


var assert = require('assert');
var ob_utils = require('utils/object_utils');

//This will load 'PegJS' module, and compile the parser syntax
//in runtime.
var load_shell_parser = require('utils/shell_parser_loader');
var parser1 = load_shell_parser();

//This will load the pre-compiled parser.
//The file should have been auto-generated by the 'Makefile'.
var parser2 = require('shell/posix_shell_parser');

var shell_syntax_tests = require('./shell_syntax_tests.js');
var tests = shell_syntax_tests.tests;


function run_test(name,input)
{
	var result_parser1 ;
	var result_parser2 ;
	try {
		result_parser1 = parser1.parse(input);
	} catch(err) {
		console.log(name + " FAIL: parser1 failed");
		return false;
	}
	try {
		result_parser2 = parser2.parse(input);
	} catch(err) {
		console.log(name + " FAIL: parser2 failed");
		return false;
	}

	assert.deepEqual(result_parser1,result_parser2);

	console.log(name + " OK");

	return true;
}

for (var t in tests)
{
	var name  = tests[t][0];
	var input = tests[t][1];
	var should_be_accepted = tests[t][2];

	if (!should_be_accepted)
		continue;

	var ok = run_test(name,input);

	if ( ok ) {
		count_pass++;
	} else {
		count_fail++;
	}
}
console.log ("--Shell Parsers comparison test--");
console.log ("pass: " + count_pass);
console.log ("fail: " + count_fail);

process.exit( count_fail>0 ) ;
